#!/usr/bin/env ruby
require 'optparse'

def create_rails_app(version, flag = nil)
  run rails_new(version, flag)
  run 'git add .'
  run "git commit -m '`#{rails_new(version, flag)}`'"
  run "git tag #{branch(version, flag)}"
  run 'git reset HEAD^'
ensure
  run 'git clean -fd'
  run 'git clean -fd'
end

def rails_new(version, flag)
  return "rails _#{version}_ new . --#{flag} --skip-bundle" if flag

  "rails _#{version}_ new . --skip-bundle"
end

def run(command)
  lcyan = "\e[1;36m"
  nocolor = "\e[0m"

  puts "#{lcyan}> #{command}#{nocolor}"

  # -- for debugging
  # print 'press any key to continue...'
  # $stdin.getc
  ret = system(command)
  raise "command failed: #{command}" unless ret
end


def filtered_versions_flags(target)
  versions_flags = {
    '6.0.4.4' => %w[
      skip-action-mailer
      skip-action-mailbox
      skip-action-text
      skip-active-record
      skip-active-storage
      skip-puma
      skip-action-cable
      skip-sprockets
      skip-spring
      skip-listen
      skip-javascript
      skip-turbolinks
      skip-test
      skip-system-test
      skip-bootsnap
      api
      webpacker
    ],
    '6.1.4.4' => %w[
      skip-action-mailer
      skip-action-mailbox
      skip-action-text
      skip-active-record
      skip-active-job
      skip-active-storage
      skip-puma
      skip-action-cable
      skip-sprockets
      skip-spring
      skip-listen
      skip-javascript
      skip-turbolinks
      skip-jbuilder
      skip-test
      skip-system-test
      skip-bootsnap
      api
      minimal
      webpacker
    ],
    '7.0.1' => %w[
      skip-action-mailer
      skip-action-mailbox
      skip-action-text
      skip-active-record
      skip-active-job
      skip-active-storage
      skip-action-cable
      skip-asset-pipeline
      asset-pipeline=sprockets
      asset-pipeline=propshaft
      skip-javascript
      skip-hotwire
      skip-jbuilder
      skip-test
      skip-system-test
      skip-bootsnap
      api
      minimal
      javascript=importmap
      javascript=webpack
      javascript=esbuild
      javascript=rollup
      css=tailwind
      css=bootstrap
      css=bulma
      css=postcss
      css=sass
    ]
  }
  return versions_flags if target == 'all'

  versions_flags.select { |k, _| k.start_with?(target) }
end

def branch(version, flag = nil)
  return [version, flag.gsub('=', '-')].compact.join('-') if flag

  version
end

target = 'all'

opt = OptionParser.new

opt.on('-t', '--target [TARGET]') do |t|
  target = t
end

opt.parse!(ARGV)
sub_command = ARGV.shift

case sub_command
when 'create'
  filtered_versions_flags(target).each do |v, flags|
    create_rails_app(v)
    flags.each do |f|
      create_rails_app(v, f)
    end
  end
when 'destroy'
  filtered_versions_flags(target).each do |v, flags|
    system "git tag -d #{branch(v)}"
    flags.each do |f|
      system "git tag -d #{branch(v, f)}"
    end
  end
when 'readme'
  repository = 'snaka/rails_new_flags'

  summary = {}
  filtered_versions_flags('all').each do |v, flags|
    flags.each do |f|
      summary[f] ||= {}
      summary[f][v] = "https://github.com/#{repository}/compare/#{branch(v)}..#{branch(v, f)}"
    end
  end

  versions = filtered_versions_flags('all').keys.sort
  flags = filtered_versions_flags('all').values.flatten.uniq.sort

  puts '| flag |' << versions.map { |v| " #{v} " }.join('|') << '|'
  puts '| --- |' << versions.count.times.map { ' --- ' }.join('|') << '|'

  diff_url = ->(url) { url ? " [🔍](#{url}) " : ' - ' }

  flags.each do |f|
    puts "| --#{f} |" << versions.map { |v| diff_url.call(summary.dig(f, v)) }.join('|') << '|'
  end
else
  puts "Usage: #{$0} [create|destroy|readme]"
end
